### ISSUE TITLE
Need a new release

### ISSUE THREAD

**Issue by jeevithakannan2** [ratatui/ansi-to-tui#54]
Projects depending on `ansi-to-tui` will not work until a new release with `ratatui 0.29.0` is released as there is a mismatch of types with `ratatui 0.29.0` and `ansi-to-tui 6.*`

![Image](https://github.com/user-attachments/assets/e5000d9f-82b2-4dac-ac4d-8e2fc702a93c)

**Comment by uttarayan21** [comment]
I've made a new release for it. with 7.* which should work

**Comment by jeevithakannan2** [comment]
Thanks for your time and quick response ❤️
